FROM docker.io/jleighsutherland/dream-base:v4

WORKDIR /app

COPY model /app/model

COPY gradio-serving.py /app/gradio-serving.py

COPY entrypoint.sh /app/entrypoint.sh

RUN pip install -r model/requirements.txt

EXPOSE 7860

CMD ["python3", "gradio-serving.py", "--predicted-features", "['eod_market_data___sbry_at_lseg__open']", "--model-name", "model_example_y", "--model-serving-url", "http://model-example-y-api-service.mlserve-model-example-y.svc.cluster.local:5000/invocations"]